### ISSUE TITLE
TIC(Today I Contribution) 포맷 만들기

### ISSUE THREAD

**Issue by Yomni** [haeuso/haeuso#10]
TIC Format을 만듭니다. 

TIC는 TIL과 비슷한 개념으로 직접 고안해 본 개념입니다.

일일 작업 일지라고 생각하시면 될 것 같습니다.

하루의 commit 중 마지막 commit을 

이 TIC 포맷에 맞춘 commit으로 작성하겠습니다.

참고자료는 [이수진님의 깃허브로 취업하기](http://sujinlee.me/professional-github/)의 commit message부분입니다.

**Comment by devJang** [comment]
오.....
안그래도 CLI 기반 커밋 포맷 지정 라이브러리가 있으니 그걸 설정하겠습니다
